name: CI/CD for MERN App

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_FRONTEND: ignus07/mernapp-frontend
  DOCKER_IMAGE_BACKEND: ignus07/mernapp-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push frontend image
      run: |
        docker build -t $DOCKER_IMAGE_FRONTEND:latest ./frontend
        docker push $DOCKER_IMAGE_FRONTEND:latest

    - name: Build and push backend image
      run: |
        docker build -t $DOCKER_IMAGE_BACKEND:latest ./backend
        docker push $DOCKER_IMAGE_BACKEND:latest

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -k k8s/
        kubectl rollout restart deployment/frontend
        kubectl rollout restart deployment/backend

